# Before You Can Work in the Lab {#training}

## Logging onto Oracle to Access Training Modules
Everyone is required to take several training modules through [Oracle](https://sso-login.vanderbilt.edu/idp/startSSO.ping?PartnerSpId=https://ecsr.login.us2.oraclecloud.com/fed). 

1. Log onto [Oracle](https://sso-login.vanderbilt.edu/idp/startSSO.ping?PartnerSpId=https://ecsr.login.us2.oraclecloud.com/fed).
2. On the home screen, click on the "Learning" button. 
3. Search for the course that you want to take. 
4. Click on "enroll" and complete the class. 
5. Take a screenshot of the completion screen for each online module and upload it into the lab's [training folder](https://drive.google.com/drive/folders/1Pbd_SUiZBgL05-BIzgbOpVR8v9ruP0hX?usp=sharing). Additionally, add your information to [this spreadsheet](https://docs.google.com/spreadsheets/d/10eLenI7HV4UPG1CfjAYf9VOY3tXPomWy_ds34bMWDcc/edit?usp=sharing).

## Required Training Modules for All Lab Members

- Biosafety 101 - annual retraining required

- Working Safely with Human Derived Specimens - annual retraining required

- Biosafety 201: Risk Assessment Applications for BSL-2 Live Course	
  - To sign up for a class, you must complete Biosafety 101. 

- Chemical and Physical Safety in the Lab - renewed annually 

- Regulated Medical Waste Shipping Training for Lab Researchers USDOT - renewed every 3-4 years and signed certificate must be kept in lab

- Biosafety Orientation Checklist & Record - must be filled out by every new lab member and copy kept in lab

## Required Training for Lab Members Conducting Animal Studies
If you are working with animals, you should also sign up for the following training modules after completing the training listed above:

1. Go to the [DAC website](https://www.vumc.org/acup/). 

2. Click [training](https://www.vumc.org/acup/iacuc/training) and log in either as VUMC or VU (depends on your home department). 

3. This [site](https://www.vumc.org/acup/acup-iacuc-required-course-information) lists all the required training. You are only required to complete sections I and IV. 

    - Section I: Complete all required training for the species you will be working with (most likely mouse) through [AALAS](https://sso.aalaslearninglibrary.org/Shibboleth.sso/Login?entityID=https://sso.service.vumc.org). 
    
    - Section IV: Register for an ACUP Animal Facility Access Tour for ESB and MCN11 7th floor. 
    
    - This [link](https://www.vumc.org/acup/acup-iacuc-recommended-courses) also contains some helpful training information. 

4. Once you complete the required training, send a copy of the transcript to Ethan. 

5. Fill out the [animal allergy survey](https://www.vumc.org/health-wellness/news-resource-articles/animal-allergy-questionnaire) if not a student or [this form](https://www.vumc.org/student-health/sites/default/files/Animal%20Allergy%20Questionnaire%20and%20IACUC%20Occ.%20Health%20Form.pdf) if a student (through student health). 

6. Once complete, let Ethan know, and he will add you to an IACUC protocol. 

7. Once approved, you will need to sign up for a facility training session. You can ask Ethan for assistance with setting up this training. 

For more information, refer to the [VUMC Animal Care and Use Program](https://www.vumc.org/acup/welcome), email [ACUP Training](mailto: acuptraining@vumc.org), or ask Ethan. 
