# Lab Values {#values}

## Lab Mission Statement
Central nervous system (CNS) diseases are a leading cause of death and disability worldwide, and their incidence is expected to increase in tandem with global life expectancies. Many available CNS therapies only ameliorate disease symptoms rather than halting or reversing the actual disease burden, and potential CNS drugs also have lower success rates at all stages of the clinical development pipeline compared to non-CNS candidates. We seek to address this issues through mechanistic investigations, high throughput screening, model system and tool development, and drug delivery. 

## Code of Conduct
The lab should be a fun and safe place for everyone to work. Any issues, personal or professional, that affect the lab environment or the well-being of any of its members should be brought to my attention *immediately.* I will do my best to promote a sense of camaraderie and accountability, but it is the responsibility of every individual to be good lab citizens. We do not tolerate poor attitudes and surly behaviors. 

We believe that racism, sexism, ableism, transphobia, homophobia, and lack of support for underrepresented minorities prevents our ability to make breakthroughs in science, and we are committed to the creation and maintenance of an equitable and inclusive environment for all of our peers.

## Responsible Conduct of Research {#RCR}
Vanderbilt and the Lippmann lab are committed to the responsible conduct of research (RCR) as described by the [NIH](https://oir.nih.gov/sourcebook/ethical-conduct/responsible-conduct-research-training). All first year students are required to take a full day of [RCR training](https://medschool.vanderbilt.edu/bret/responsible-conduct-research/) by the start of their second year. This training is expected to be ongoing every year. Additional RCR courses throughout the year can be found on the BRET office's [calendar](https://medschool.vanderbilt.edu/bret/seminar-series-calendar/) as well as through the [CITI Program](https://about.citiprogram.org/en/series/responsible-conduct-of-research-rcr/). Breaches in RCR will be addressed seriously and can potential result in dismissal from the lab.  

## Resources
### Graduate Student and Postdoctoral Fellow Organizations
- [Graduate Student Council](https://studentorg.vanderbilt.edu/gsc/)

- [Vanderbilt Biomedical Engineering Graduate Student Association](https://anchorlink.vanderbilt.edu/organization/bme_gsa)

- [Vanderbilt Chemical Engineering Graduate Student Association](https://engineering.vanderbilt.edu/chbe/GraduateProgram/CHEGSA.php)

- [Neuroscience Student Organization](https://medschool.vanderbilt.edu/brain-institute/new-vbi-homepage-inprogress/resources-for-students/neuroscience-student-organization/)

- [Graduate Leadership Institute](https://gradschool.vanderbilt.edu/gli/)

- [Vanderbilt Postdoc Association](https://www.vanderbilt.edu/vpa/index.php)

- [Office of Postdoctoral Affairs](https://www.vanderbilt.edu/postdoc/)

- [AnchorLink](https://anchorlink.vanderbilt.edu/) - good place to look for other student-lead organizations at Vanderbilt

### Diversity and Inclusion Organizations 
- [Office for Equity, Diversity, and Inclusion](https://www.vanderbilt.edu/diversity/contact/)

- [Office of Inclusive Excellence](https://www.vanderbilt.edu/inclusive-excellence/index.php)

- [Student Center for Social Justice & Identity](https://www.vanderbilt.edu/scsji/)

- [Women's Center](https://www.vanderbilt.edu/WomensCenter/)

- [LGBTQI Life](https://www.vanderbilt.edu/lgbtqi/)

- [Black Cultural Center](https://www.vanderbilt.edu/bcc/)

- [Office of University Chaplain and Religious Life](https://www.vanderbilt.edu/religiouslife/)

- [Vanderbilt University Women in Science & Engineering](https://my.vanderbilt.edu/vuwise/)

- [Nashville Chapter of Graduate Women in Science](https://gwisnashville.wixsite.com/gwisnashville)

- [Vanderbilt GoSTEM](https://www.vanderbilt.edu/lgbtqi/programs/student-groups)

### Career Development 
- [The Office of Biomedical Research Education & Training](https://medschool.vanderbilt.edu/bret/resources/)

- [Career Center](https://www.vanderbilt.edu/career/)

### Mental and Physical Health Services
- [Student Health Center](https://www.vumc.org/student-health/welcome)

- [University Counseling Center](https://www.vanderbilt.edu/ucc/)

- [Office of Student Care Coordination](https://www.vanderbilt.edu/carecoordination/)

- [Vanderbilt Project Safe](https://www.vanderbilt.edu/projectsafe/)

- [Student Care Network](https://www.vanderbilt.edu/studentcarenetwork/)

- [Center for Student Wellbeing](https://www.vanderbilt.edu/healthydores/)

- [Graduate Life Coach](https://gradschool.vanderbilt.edu/current_students/gradlife.php)
