# Data Management and Shared Resources {#datamanagement}
This section will describe how the Lippmann Lab stores and manages data. 

## Storage and Documentation 
### Lab Shared Network Drive
Our lab has a shared network drive folder where members of the lab can store raw data. You should have requested access to this folder in the [Accessing Lab Accounts and Spaces]{#access} section of this document. The address of this folder is smb://vu1file.it.vanderbilt.edu/lippmannlab/. In order to log in, you will need to type "VANDERBILT/Your NetID" for the username and your normal Vanderbilt password for the first password. If it is your first time logging in, you should set up a folder with your name. This is a communal resource, so everyone has access to your files once you've uploaded them to the drive. Make sure you are saving your files to this location from the Leica microscope or you are using your own external drive as storage space on the Leica computer is limited. Some members of the lab also use this as backup for important documents such as qualifying exams, fellowship applications, etc. 

#### Other Shared Access Drives
Many [core facilities](#corefacilities) also have their own folders for storing and managing data. You can check each core facility's website to find the address for its specific folder. Additionally, the Bellan lab has it's own folder for saving confocal data; you will need to ask a Bellan lab member for access to this remote folder. 

#### Remote Access Using Pulse Virtual Private Network (VPN)
If you want to access data saved in these folders off-campus, you will need to set up [Pulse VPN](https://it.vanderbilt.edu/services/catalog/end-point_computing/network_access/remote-access/index.php). Note that you will need [Duo Multi-Factor Authentification](#duo) set up to use the Pulse VPN service. If you are on campus and connected to the Vanderbilt WiFi, you should be able to open these folders without connecting to the VPN. 

### Google Drive 
The [lab Google Drive folder](https://drive.google.com/drive/folders/0Bwvn9S-4oeMmeHhzUS1nM0FNak0?usp=sharing) is another storage site commonly used to share information with the entire lab. This information includes locations of reagents, protocols, and example fellowship/qualifying exam documents. Lab members generally do not use this space to store data. You should be updating these files if you move or receive reagents or if you develop any protocols for the lab. 

### Vanderbilt Box
[Vanderbilt Box](https://vanderbilt.account.box.com/login) is where most data and document sharing with Ethan occurs. You should use your normal VU NetID and password to log into this account. If this is your fist time logging in, you should make a folder entitled "[Your Name] Research" and share it with Ethan. This is where research updates, subgroup meeting presentations, raw paper data, etc. is stored. ***Once you have submitted a paper, make sure that Ethan has all the raw data in a Box folder in order to comply with RCR standards!***

### GitHub 
The [Lippmann Lab GitHub](https://github.com/lippmannlab) is where code sharing occurs. There are different repositories for different programs that lab members use to quantify their data or control their bioreactors. Generally, the repositories that involve quantifying data stores a README file that explains how to install and use the code, all the code needed to run the program, and an example file to run the code with. If you edit any part of these repositories, make sure your commit messages are detailed enough that others can understand what changes you have made. If you are creating a new repository, follow the "Neuron Image Processor" as a template for what should be included. Public repositories such as the Spinfinity code does not require a GitHub account to access, but any private repositories will require that you create an account and that a lab member adds you as a collaborator to the project. 

### Computer Back Ups
You should be backing up your computer relatively frequently. This can take many forms but can be extremely useful if your computer crashes or you accidentally delete data. 

## Reference Management {#zotero}
Most members of the lab use [Zotero](https://www.zotero.org/) as their reference manager. You should [download](https://www.zotero.org/download/) the program to your computer at the beginning of your graduate training. Additionally, it is helpful to install the Chrome connector, which allows you to easily save papers that you are reading to Zotero. Furthermore, Zotero has plugins for both [Word](https://www.zotero.org/support/word_processor_plugin_usage) and [Google Docs](https://www.zotero.org/support/google_docs) that will allow you to insert both citations and bibliographies effortlessly into papers. Zotero allows you to format your citations and bibliographies in a variety of different citation styles, and you can easily convert your settings in the same document. 

Another free reference manager that some lab members use is [Mendeley](https://www.mendeley.com/download-desktop-new/), although it is much easier to have everyone using the same program when writing papers in groups. 

Furthermore, this [Excel Journal Database](https://www.youtube.com/watch?v=Y40Wy1guAiQ) may also be a good tool for keeping up with what papers you have read during your training, although it should not be used as your citation manager. 

## Communication 
This section will contain tips on how to present scientific work. An entire chapter is dedicated to writing manuscripts. 

### Creating an Oral Presentation 
All graduate students and postdocs will present a research update once a semester at the lab group meeting. Additionally, lab members may have the opportunity to speak at department retreats, seminars, and conferences. 

- 

#### Journal Club Presentations
The lab rotates who presents an article for our lab's journal club, which is usually emailed out at the beginning of each semester. There are also other opportunities to present at other journal clubs on campus such as at the Alzheimer's Disease Journal Club.

- **Picking an article to present:** You should choose a paper that has been published relatively recently. Ethan will typically assist younger students before their first presentation. 

- **P

### Creating a Poster Presentation 

[Better poster movement](https://www.insidehighered.com/news/2019/06/24/theres-movement-better-scientific-posters-are-they-really-better)

## Computation/Data Analysis
- software, norms for analysis
- scripting (language), version control 
- documentation 
