# How to Contribute to the Onboarding Document {#contribute}
This onboarding document is expected to be a dynamic document that will change over time. As such, the Lippmann Lab will work as a team to keep it up-to-date. Here are a few ways that individual members can help suggest edits or create changes to the onboarding document. 

## Not Comfortable With Coding
If you are not comfortable with coding or GitHub, you can create an "Issue" in the GitHub repository to suggest edits to the document. 

1. Create a [GitHub account](https://github.com/). 

2. Navigate to the [Lippmann Lab Onboarding Repository](). 

3. Choose the "Issues" tab in the repository and create a new issue. 

4. A lab member in charge of maintaining the document will look over your issue when they have time and incorporate any changes needed to the document. They may be in touch with you if you are interested in adding an additional section to the onboarding document. 

## Comfortable with GitHub
If you are comfortable with using GitHub and the LaTEX/markdown language, you can suggest edits directly to the GitHub Repository. 

1. Navigate to the [Lippmann Lab Onboarding Repository](). 

2. Select the specific chapter(s) that you want to edit. You should select the .Rmd file rather than the .html file.  

3. Click the pencil button to start editing. 

4. Add your edits. Add a descriptive commit message so that the person reviewing your edit knows what you changed and why. Select "Create a new branch for this commit and start a pull request." Commit your changes. 

5. A lab member who is in charge of maintaining this document will review your pull request and either discuss the change(s) with your or accept your changes. 

## Interested in Assisting the Document Maintenance 
At least one lab member will be in charge of directly editing the document. If you are interested in becoming in charge of maintaining the onboarding document, talk to Ethan or senior lab members to schedule training. No prior experience is necessary - just an interest in learning!
