# Manuscript Preparation 
Your papers are your currency from your time in the lab - peer-reviewed proof that you are are highly skilled and successful researcher. As such, the final versions should be clear and concise but thorough and polished. Read a few papers Ethan published during graduate school and his postdoctoral fellowship ([Lippmann et al, *Stem Cells,* 2014](https://stemcellsjournals-onlinelibrary-wiley-com.proxy.library.vanderbilt.edu/doi/full/10.1002/stem.1622); [Lippmann et al, *Nat Biotechnol,* 2012](https://www-nature-com.proxy.library.vanderbilt.edu/articles/nbt.2247)) to get an idea of the style he prefers. Additionally you can see a list of the papers that have been published by members of the lab [here](http://www.lippmannlab.com/publications).

## The Process

1. **Outline the paper.** In general, I prefer that you meet with me to discuss an outline of the paper, most notably the general message of the introduction and how the data/figures will support the claims made, prior to initiating the writing process. It is common to think about your existing data, figure sets, and missing pieces before starting the writing process.

2. **Pick a target journal.** For obvious reasons, not everything gets submitted to Nature or Science. Have a good idea for what you think the significance of your work is, whether it belongs in a broad journal versus a specialty journal, and how quickly you want to get it published. 

3. **Read the journal's author guidelines.** Most journals have their own specific figure guidelines and word limits. Unless you want to tear your hair out reformatting, check the journal requirements first. 

4. **You will write the first draft - Ethan will be heavily involved in your first paper-writing attempt but preferably less so therafter.** Some re-writing by me is inevitable, but I try to be constructive if I don't agree with the language you've used or the conclusions you've drawn. The first draft typically gets marked up a lot, and subsequent edits are much faster. 

5. **Track changes as best you can between versions.** If you don't agree with a change I have made, make a comment in the document so I don't think you're just ignoring my opinion. Save each version as a different file in case you need to go back to something written in an earlier version. 

6. **Assemble your figures in Photoshop or Illustrator.** Most journals require a certain resolution and may have their own requirements on fonts and sizes. I typically do all of my figure preparations, including labels, in PowerPoint and then assemble these parts in Photoshop at the desired figure resolution (typically 300-400 dpi). After assembly, images can be compressed by flattening the layers into one final plane. Most journals also require images to be below a certain size (usually 10MB). 
    
    - The lab has a [Biorender](https://biorender.com/) license, so you can ask Ethan to get access to the program in order to make figures.
    
    - [Vanderbilt IT Software Store](https://it.vanderbilt.edu/software-store/index.php) provides free software to students, staff, and faculty including Microsoft Office 365 ProPlus and ChemBioDraw as well as discounted subscriptions for programs like Adobe Photoshop and Prism. If you think a program would be broadly beneficial for the lab to purchase a license for, discuss it with Ethan. 

7. **After assembling the figures and submitting the paper, provide Ethan with the figures** ***minus*** **their lettering (a, b, c, etc.).** This makes it easier to use these figures for presentations. 

8. **Any data used to compile a graph of some sort should be provided to Ethan in an Excel spreadsheet.** This ensures that he has a copy of the original numbers after you leave, complying with [RCR practices](#RCR). Many students choose to set a folder for their manuscripts in [Box](http://vanderbilt.box.com/) that contains raw and processed data.

9. ***Once you have submitted a paper, make sure that Ethan has all the raw data in a Box folder in order to comply with RCR standards!***

10. **Celebrate when the paper is accepted.** First round for the entire lab is always on Ethan! It is important to revel in the success of your colleagues. 

## Writing Resources 

- The university has a few writing accountability programs including [WAG](https://www.vanderbilt.edu/healthydores/writers-accountability-group-wag-workshop/).

- The university also provides a [writing studio](https://www.vanderbilt.edu/writing/) where you can get feedback on your manuscripts. The BRET office lists additional [resources](https://medschool.vanderbilt.edu/postdoc/vanderbilt-resources/scientific-writing/) that are available for improving scientific writing. 
